version: 2.1

jobs:
  build:
    docker:
      - image: debian:bookworm
    resource_class: arm.large
    environment:
      DEBIAN_FRONTEND: noninteractive
      # Executors on CircleCI report incorrect number of cores, so we
      # need to set it manually.
      CPU_COUNT: 4

    steps:
      - checkout

      - run:
          name: Prepare build environment
          command: |
            apt-get update
            apt-get install -y git
            ./install-deps
            ./bootstrap
            ./configure --without-gtkmm

      - run:
          name: Build
          command: make -j${CPU_COUNT}

      - run:
          name: Create tarball
          command: XZ_OPT="--threads=${CPU_COUNT}" tar --exclude-vcs -Jcvf /tmp/utsushi.tar.xz .

      - store_artifacts:
          path: /tmp/utsushi.tar.xz
          destination: utsushi.tar.xz

workflows:
  run-jobs:
    jobs:
      - build
